---
version: 2.1
publish: &publish
  working_directory: ~/repo
  docker:
    - image: circleci/node:12.0.0
  steps:
    - checkout
    - restore_cache:
        name: Restore npm package cache
        key: v1-cache-dependencies-{{ checksum "package-lock.json" }}-{{ checksum  "package.json" }}-{{ arch }}
    - run:
        name: Installing dependencies
        command: npm ci
    - save_cache:
        name: Save npm package cache
        paths:
          - ~/.cache/npm
        key: v1-cache-dependencies-{{ checksum "package-lock.json" }}-{{ checksum  "package.json" }}-{{ arch }}
    - run:
        name: Run tests
        command: npm run test
    - run:
        name: Login into Expo
        command: npx expo-cli login -u $EXPO_USERNAME -p $EXPO_PASSWORD
    - run:
        name: Publish to Expo
        command: npx expo-cli publish --non-interactive --max-workers 1 --release-channel $EXPO_RELEASE_CHANNEL

jobs:
  publish_to_expo_dev:
    context: app
    environment:
      EXPO_RELEASE_CHANNEL: dev
    <<: *publish

  publish_to_expo_prod:
    context: app
    environment:
      EXPO_RELEASE_CHANNEL: default
    <<: *publish

workflows:
  version: 2
  easy-control-app:
    jobs:
      - publish_to_expo_dev:
          filters:
            branches:
              only: development
      - publish_to_expo_prod:
          filters:
            branches:
              only: master
